-- schema/030_embedding_backfill_runs.sql
-- Hivemind hybrid search · Phase 2 task 2.11
--
-- Embedding backfill lifecycle surface. Introduces two owner-only tables that
-- record run/progress state plus a frozen, SECURITY DEFINER RPC API used by the
-- orchestrator. The contract is additive and idempotent: re-applying is a
-- no-op once the objects exist.
--
-- Security contract:
--   * PUBLIC, anon, and authenticated are revoked on every object.
--   * service_role is granted the access needed to drive a backfill.
--   * All mutation RPCs are SECURITY DEFINER with search_path = public, pg_temp.
--   * No source corpus table is touched here.
--   * Raw bearer / sk- secrets are never persisted; a sanitizer strips them.
--
-- APPLY:    psql "$DATABASE_URL" -f schema/030_embedding_backfill_runs.sql
-- ROLLBACK: see the literal DROP block at the bottom of this file.

-- ===========================================================================
-- 1. Sanitizer helper
--
-- Stable, deterministic scrubber used by every mutation RPC before any error
-- text is persisted. Order matters: redact secrets first, then strip control
-- characters, then bound the length.
-- ===========================================================================
create or replace function public.hivemind_sanitize_backfill_error(p_text text)
returns text
language sql
immutable
as $$
    select left(
        btrim(
            regexp_replace(
                regexp_replace(
                    regexp_replace(
                        coalesce(p_text, ''),
                        '(?i)authorization:[ \t]*bearer[ \t]+[A-Za-z0-9._\-/+=]+',
                        'Authorization: Bearer [REDACTED]',
                        'g'
                    ),
                    'sk-[A-Za-z0-9._\-/+=]+',
                    'sk-[REDACTED]',
                    'g'
                ),
                '[\x00-\x1F\x7F]',
                ' ',
                'g'
            )
        ),
        500
    );
$$;

-- ===========================================================================
-- 2. Tables
-- ===========================================================================
create table if not exists public.embedding_backfill_runs (
    run_id                bigint generated by default as identity primary key,
    contract_id           bigint not null references public.embedding_contracts(id),
    version               integer not null default 1,
    mode                  text not null
                          check (mode in ('full', 'incremental', 'catchup', 'rebuild')),
    status                text not null default 'running'
                          check (status in ('running', 'paused', 'completed', 'failed')),
    snapshot              text,
    high_water            text,
    batch_size            integer,
    rate_limit_per_minute integer,
    cost_cap_usd          numeric,
    -- Aggregate counters (names are part of the frozen contract).
    total_eligible        bigint not null default 0 check (total_eligible >= 0),
    total_processed       bigint not null default 0 check (total_processed >= 0),
    total_skipped         bigint not null default 0 check (total_skipped >= 0),
    total_quarantined     bigint not null default 0 check (total_quarantined >= 0),
    total_unavailable     bigint not null default 0 check (total_unavailable >= 0),
    total_failed          bigint not null default 0 check (total_failed >= 0),
    last_error            text check (length(last_error) <= 500),
    -- Lifecycle timestamps.
    created_at            timestamptz not null default now(),
    updated_at            timestamptz not null default now(),
    paused_at             timestamptz,
    resumed_at            timestamptz,
    completed_at          timestamptz,
    failed_at             timestamptz
);

comment on table public.embedding_backfill_runs is
    'Lifecycle record for an embedding backfill execution (task 2.11).';

create table if not exists public.embedding_backfill_cursors (
    run_id            bigint not null references public.embedding_backfill_runs(run_id)
                      on delete cascade,
    source            text not null,
    cursor            text,
    high_water        text,
    -- Per-source counters (names are part of the frozen contract).
    eligible_count    bigint not null default 0 check (eligible_count >= 0),
    processed_count   bigint not null default 0 check (processed_count >= 0),
    skipped_count     bigint not null default 0 check (skipped_count >= 0),
    quarantined_count bigint not null default 0 check (quarantined_count >= 0),
    unavailable_count bigint not null default 0 check (unavailable_count >= 0),
    failed_count      bigint not null default 0 check (failed_count >= 0),
    last_error        text check (length(last_error) <= 500),
    updated_at        timestamptz not null default now(),
    primary key (run_id, source)
);

create index if not exists embedding_backfill_cursors_run_idx
    on public.embedding_backfill_cursors(run_id);

comment on table public.embedding_backfill_cursors is
    'Per-source progress cursor for an embedding backfill run (task 2.11).';

-- ===========================================================================
-- 3. hivemind_create_embedding_backfill_run
--
-- Inserts a running version-1 run plus one zeroed cursor row per distinct
-- nonblank source. Empty source lists are rejected (the run is rolled back).
-- ===========================================================================
create or replace function public.hivemind_create_embedding_backfill_run(
    p_contract_id bigint,
    p_mode        text,
    p_sources     text[]
) returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_run_id   bigint;
    v_inserted integer;
begin
    insert into public.embedding_backfill_runs (contract_id, mode, status, version)
    values (p_contract_id, p_mode, 'running', 1)
    returning run_id into v_run_id;

    insert into public.embedding_backfill_cursors (
        run_id, source, cursor, high_water,
        eligible_count, processed_count, skipped_count,
        quarantined_count, unavailable_count, failed_count)
    select
        v_run_id, d.s, null, null,
        0, 0, 0, 0, 0, 0
    from (
        select distinct source as s
        from unnest(coalesce(p_sources, array[]::text[])) as u(source)
        where source is not null and btrim(source) <> ''
    ) d;
    get diagnostics v_inserted = row_count;

    if v_inserted = 0 then
        -- Reject empty source lists: leave no orphan run behind.
        delete from public.embedding_backfill_runs where run_id = v_run_id;
        raise exception 'embedding_backfill: empty source list';
    end if;

    return v_run_id;
end;
$$;

-- ===========================================================================
-- 4. hivemind_checkpoint_embedding_backfill
--
-- Atomic compare-and-set checkpoint. Under row lock on the run (and then on
-- the source cursor) it requires status = 'running' and an exact version
-- match, applies nonnegative deltas to both cursor and aggregate counters,
-- advances the text cursor, preserves high_water when null, stores only a
-- bounded sanitized error, and bumps the run version exactly once.
--
-- On any rejection (missing run, missing source, terminal status, stale CAS)
-- nothing is mutated and a {"ok":false,...} payload describing the current
-- version/status is returned without raising.
-- ===========================================================================
create or replace function public.hivemind_checkpoint_embedding_backfill(
    p_run_id           bigint,
    p_source           text,
    p_expected_version integer,
    p_cursor           text,
    p_high_water       text,
    p_processed        bigint,
    p_skipped          bigint,
    p_quarantined      bigint,
    p_unavailable      bigint,
    p_failed           bigint,
    p_eligible         bigint,
    p_last_error       text
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_version integer;
    v_status  text;
    v_proc    bigint := coalesce(p_processed, 0);
    v_skip    bigint := coalesce(p_skipped, 0);
    v_quar    bigint := coalesce(p_quarantined, 0);
    v_unav    bigint := coalesce(p_unavailable, 0);
    v_fail    bigint := coalesce(p_failed, 0);
    v_elig    bigint := coalesce(p_eligible, 0);
    v_err     text;
begin
    if v_proc < 0 or v_skip < 0 or v_quar < 0 or v_unav < 0 or v_fail < 0 or v_elig < 0 then
        return jsonb_build_object('ok', false, 'reason', 'negative_delta');
    end if;

    -- Lock the run row first.
    select r.version, r.status into v_version, v_status
    from public.embedding_backfill_runs r
    where r.run_id = p_run_id
    for update of r;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'missing_run');
    end if;

    if v_status <> 'running' then
        return jsonb_build_object(
            'ok', false, 'reason', 'not_running',
            'version', v_version, 'status', v_status);
    end if;

    if v_version is distinct from p_expected_version then
        return jsonb_build_object(
            'ok', false, 'reason', 'stale_version',
            'version', v_version, 'status', v_status);
    end if;

    -- Lock the source cursor row; reject unknown sources without mutating.
    perform 1
    from public.embedding_backfill_cursors c
    where c.run_id = p_run_id and c.source = p_source
    for update of c;
    if not found then
        return jsonb_build_object(
            'ok', false, 'reason', 'missing_source',
            'version', v_version, 'status', v_status);
    end if;

    v_err := public.hivemind_sanitize_backfill_error(p_last_error);

    update public.embedding_backfill_cursors
      set cursor            = coalesce(p_cursor, cursor),
           high_water        = coalesce(p_high_water, high_water),
           eligible_count    = eligible_count    + v_elig,
           processed_count   = processed_count   + v_proc,
           skipped_count     = skipped_count     + v_skip,
           quarantined_count = quarantined_count + v_quar,
           unavailable_count = unavailable_count + v_unav,
           failed_count      = failed_count      + v_fail,
           last_error        = v_err,
           updated_at        = now()
     where run_id = p_run_id and source = p_source;

    update public.embedding_backfill_runs
      set version           = version + 1,
           high_water        = coalesce(p_high_water, high_water),
           total_eligible    = total_eligible    + v_elig,
           total_processed   = total_processed   + v_proc,
           total_skipped     = total_skipped     + v_skip,
           total_quarantined = total_quarantined + v_quar,
           total_unavailable = total_unavailable + v_unav,
           total_failed      = total_failed      + v_fail,
           last_error        = v_err,
           updated_at        = now()
     where run_id = p_run_id
     returning version into v_version;

    return jsonb_build_object(
        'ok', true, 'reason', 'checkpointed',
        'version', v_version, 'status', 'running',
        'source', p_source);
end;
$$;

-- ===========================================================================
-- 5. Lifecycle RPCs: pause / resume / complete / fail
--
-- Each is a compare-and-set: lock the run, require the expected transition,
-- bump the version exactly once, and never advance a terminal run. Stale CAS
-- or missing runs return {"ok":false,...} with the current version/status.
-- ===========================================================================
create or replace function public.hivemind_pause_embedding_backfill_run(
    p_run_id           bigint,
    p_expected_version integer
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_version integer;
    v_status  text;
begin
    select r.version, r.status into v_version, v_status
    from public.embedding_backfill_runs r
    where r.run_id = p_run_id
    for update of r;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'missing_run');
    end if;

    if v_status <> 'running' then
        return jsonb_build_object(
            'ok', false, 'reason', 'not_running',
            'version', v_version, 'status', v_status);
    end if;

    if v_version is distinct from p_expected_version then
        return jsonb_build_object(
            'ok', false, 'reason', 'stale_version',
            'version', v_version, 'status', v_status);
    end if;

    update public.embedding_backfill_runs
       set status = 'paused', version = version + 1,
           paused_at = now(), updated_at = now()
     where run_id = p_run_id
     returning version, status into v_version, v_status;

    return jsonb_build_object(
        'ok', true, 'reason', 'paused',
        'version', v_version, 'status', v_status);
end;
$$;

create or replace function public.hivemind_resume_embedding_backfill_run(
    p_run_id           bigint,
    p_expected_version integer
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_version integer;
    v_status  text;
begin
    select r.version, r.status into v_version, v_status
    from public.embedding_backfill_runs r
    where r.run_id = p_run_id
    for update of r;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'missing_run');
    end if;

    if v_status <> 'paused' then
        return jsonb_build_object(
            'ok', false, 'reason', 'not_paused',
            'version', v_version, 'status', v_status);
    end if;

    if v_version is distinct from p_expected_version then
        return jsonb_build_object(
            'ok', false, 'reason', 'stale_version',
            'version', v_version, 'status', v_status);
    end if;

    update public.embedding_backfill_runs
       set status = 'running', version = version + 1,
           resumed_at = now(), updated_at = now()
     where run_id = p_run_id
     returning version, status into v_version, v_status;

    return jsonb_build_object(
        'ok', true, 'reason', 'resumed',
        'version', v_version, 'status', v_status);
end;
$$;

create or replace function public.hivemind_complete_embedding_backfill_run(
    p_run_id           bigint,
    p_expected_version integer
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_version integer;
    v_status  text;
begin
    select r.version, r.status into v_version, v_status
    from public.embedding_backfill_runs r
    where r.run_id = p_run_id
    for update of r;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'missing_run');
    end if;

    if v_status not in ('running', 'paused') then
        return jsonb_build_object(
            'ok', false, 'reason', 'not_completable',
            'version', v_version, 'status', v_status);
    end if;

    if v_version is distinct from p_expected_version then
        return jsonb_build_object(
            'ok', false, 'reason', 'stale_version',
            'version', v_version, 'status', v_status);
    end if;

    update public.embedding_backfill_runs
       set status = 'completed', version = version + 1,
           completed_at = now(), updated_at = now()
     where run_id = p_run_id
     returning version, status into v_version, v_status;

    return jsonb_build_object(
        'ok', true, 'reason', 'completed',
        'version', v_version, 'status', v_status);
end;
$$;

create or replace function public.hivemind_fail_embedding_backfill_run(
    p_run_id           bigint,
    p_expected_version integer,
    p_error            text
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_version integer;
    v_status  text;
    v_err     text;
begin
    select r.version, r.status into v_version, v_status
    from public.embedding_backfill_runs r
    where r.run_id = p_run_id
    for update of r;

    if not found then
        return jsonb_build_object('ok', false, 'reason', 'missing_run');
    end if;

    if v_status not in ('running', 'paused') then
        return jsonb_build_object(
            'ok', false, 'reason', 'not_failable',
            'version', v_version, 'status', v_status);
    end if;

    if v_version is distinct from p_expected_version then
        return jsonb_build_object(
            'ok', false, 'reason', 'stale_version',
            'version', v_version, 'status', v_status);
    end if;

    v_err := public.hivemind_sanitize_backfill_error(p_error);

    update public.embedding_backfill_runs
       set status = 'failed', version = version + 1,
           last_error = v_err,
           failed_at = now(), updated_at = now()
     where run_id = p_run_id
     returning version, status into v_version, v_status;

    return jsonb_build_object(
        'ok', true, 'reason', 'failed',
        'version', v_version, 'status', v_status);
end;
$$;

-- ===========================================================================
-- 6. ACL (literal, auditable security contract)
--
-- The literal REVOKEs from anon/authenticated and GRANTs to service_role are
-- intentionally spelled out below. Roles are not created here; this migration
-- assumes the standard Supabase roles (anon, authenticated, service_role).
-- ===========================================================================
revoke all on public.embedding_backfill_runs from public;
revoke all on public.embedding_backfill_cursors from public;
revoke all on sequence public.embedding_backfill_runs_run_id_seq from public;
revoke execute on function public.hivemind_sanitize_backfill_error(text) from public;
revoke execute on function public.hivemind_create_embedding_backfill_run(bigint, text, text[]) from public;
revoke execute on function public.hivemind_checkpoint_embedding_backfill(bigint, text, integer, text, text, bigint, bigint, bigint, bigint, bigint, bigint, text) from public;
revoke execute on function public.hivemind_pause_embedding_backfill_run(bigint, integer) from public;
revoke execute on function public.hivemind_resume_embedding_backfill_run(bigint, integer) from public;
revoke execute on function public.hivemind_complete_embedding_backfill_run(bigint, integer) from public;
revoke execute on function public.hivemind_fail_embedding_backfill_run(bigint, integer, text) from public;

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'anon') then
        execute 'revoke all on public.embedding_backfill_runs from anon';
        execute 'revoke all on public.embedding_backfill_cursors from anon';
        execute 'revoke all on sequence public.embedding_backfill_runs_run_id_seq from anon';
        execute 'revoke execute on function public.hivemind_sanitize_backfill_error(text) from anon';
        execute 'revoke execute on function public.hivemind_create_embedding_backfill_run(bigint, text, text[]) from anon';
        execute 'revoke execute on function public.hivemind_checkpoint_embedding_backfill(bigint, text, integer, text, text, bigint, bigint, bigint, bigint, bigint, bigint, text) from anon';
        execute 'revoke execute on function public.hivemind_pause_embedding_backfill_run(bigint, integer) from anon';
        execute 'revoke execute on function public.hivemind_resume_embedding_backfill_run(bigint, integer) from anon';
        execute 'revoke execute on function public.hivemind_complete_embedding_backfill_run(bigint, integer) from anon';
        execute 'revoke execute on function public.hivemind_fail_embedding_backfill_run(bigint, integer, text) from anon';
    end if;

    if exists (select 1 from pg_roles where rolname = 'authenticated') then
        execute 'revoke all on public.embedding_backfill_runs from authenticated';
        execute 'revoke all on public.embedding_backfill_cursors from authenticated';
        execute 'revoke all on sequence public.embedding_backfill_runs_run_id_seq from authenticated';
        execute 'revoke execute on function public.hivemind_sanitize_backfill_error(text) from authenticated';
        execute 'revoke execute on function public.hivemind_create_embedding_backfill_run(bigint, text, text[]) from authenticated';
        execute 'revoke execute on function public.hivemind_checkpoint_embedding_backfill(bigint, text, integer, text, text, bigint, bigint, bigint, bigint, bigint, bigint, text) from authenticated';
        execute 'revoke execute on function public.hivemind_pause_embedding_backfill_run(bigint, integer) from authenticated';
        execute 'revoke execute on function public.hivemind_resume_embedding_backfill_run(bigint, integer) from authenticated';
        execute 'revoke execute on function public.hivemind_complete_embedding_backfill_run(bigint, integer) from authenticated';
        execute 'revoke execute on function public.hivemind_fail_embedding_backfill_run(bigint, integer, text) from authenticated';
    end if;

    if exists (select 1 from pg_roles where rolname = 'service_role') then
        execute 'grant select, insert, update, delete on public.embedding_backfill_runs to service_role';
        execute 'grant select, insert, update, delete on public.embedding_backfill_cursors to service_role';
        execute 'grant usage, select on sequence public.embedding_backfill_runs_run_id_seq to service_role';
        execute 'grant execute on function public.hivemind_sanitize_backfill_error(text) to service_role';
        execute 'grant execute on function public.hivemind_create_embedding_backfill_run(bigint, text, text[]) to service_role';
        execute 'grant execute on function public.hivemind_checkpoint_embedding_backfill(bigint, text, integer, text, text, bigint, bigint, bigint, bigint, bigint, bigint, text) to service_role';
        execute 'grant execute on function public.hivemind_pause_embedding_backfill_run(bigint, integer) to service_role';
        execute 'grant execute on function public.hivemind_resume_embedding_backfill_run(bigint, integer) to service_role';
        execute 'grant execute on function public.hivemind_complete_embedding_backfill_run(bigint, integer) to service_role';
        execute 'grant execute on function public.hivemind_fail_embedding_backfill_run(bigint, integer, text) to service_role';
    end if;
end
$$;

-- ===========================================================================
-- 7. Read-only verification helpers (commented; run manually if desired).
-- ===========================================================================
-- select public.hivemind_sanitize_backfill_error(
--          'Authorization: Bearer sk-secret-DO-NOT-STORE oops');
-- -- expected: 'Authorization: Bearer [REDACTED] sk-[REDACTED] oops'
--
-- select to_regclass('public.embedding_backfill_runs')        as runs_tbl,
--        to_regclass('public.embedding_backfill_cursors')     as cursors_tbl,
--        to_regprocedure('public.hivemind_create_embedding_backfill_run(bigint,text,text[])') as create_rpc;

-- ===========================================================================
-- 8. ROLLBACK
--
-- Drop only the objects created by this migration, in safe dependency order
-- (RPCs first, then cursors, then runs, then the sanitizer helper). Run
-- manually; this file does not auto-execute the rollback.
-- ===========================================================================
-- ROLLBACK:
-- drop function if exists public.hivemind_fail_embedding_backfill_run(bigint, integer, text);
-- drop function if exists public.hivemind_complete_embedding_backfill_run(bigint, integer);
-- drop function if exists public.hivemind_resume_embedding_backfill_run(bigint, integer);
-- drop function if exists public.hivemind_pause_embedding_backfill_run(bigint, integer);
-- drop function if exists public.hivemind_checkpoint_embedding_backfill(bigint, text, integer, text, text, bigint, bigint, bigint, bigint, bigint, bigint, text);
-- drop function if exists public.hivemind_create_embedding_backfill_run(bigint, text, text[]);
-- drop function if exists public.hivemind_sanitize_backfill_error(text);
-- drop table if exists public.embedding_backfill_cursors;
-- drop table if exists public.embedding_backfill_runs;
-- end ROLLBACK.
