-- Durable, owner-only lifecycle for task 2.12 workflow representation repair.
-- This state is deliberately separate from embedding contracts/runs and from
-- source metadata.  It is additive/idempotent and stores only opaque ids,
-- cursors, counters, and bounded reason codes -- never source/Python bodies.

create table if not exists public.workflow_remediation_runs (
    run_id bigint generated by default as identity primary key,
    version integer not null default 1 check (version > 0),
    status text not null default 'running' check (status in ('running','completed','failed')),
    high_water bigint,
    processed_count bigint not null default 0 check (processed_count >= 0),
    materialized_count bigint not null default 0 check (materialized_count >= 0),
    skipped_count bigint not null default 0 check (skipped_count >= 0),
    unavailable_count bigint not null default 0 check (unavailable_count >= 0),
    failed_count bigint not null default 0 check (failed_count >= 0),
    created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
    completed_at timestamptz
);

create table if not exists public.workflow_remediation_cursors (
    run_id bigint primary key references public.workflow_remediation_runs(run_id) on delete cascade,
    cursor bigint, high_water bigint,
    last_reason text check (last_reason is null or last_reason in ('corpus_path_unauthorized','conversion_error')),
    updated_at timestamptz not null default now()
);

create table if not exists public.workflow_remediation_failures (
    run_id bigint not null references public.workflow_remediation_runs(run_id) on delete cascade,
    resource_id bigint not null,
    reason text not null check (reason in ('corpus_path_unauthorized','conversion_error')),
    attempts bigint not null default 1 check (attempts > 0),
    updated_at timestamptz not null default now(),
    primary key (run_id, resource_id)
);

create or replace function public.hivemind_create_workflow_remediation_run(p_high_water bigint)
returns bigint language plpgsql security definer set search_path=public,pg_temp as $$
declare v_run bigint;
begin
  insert into public.workflow_remediation_runs(high_water) values(p_high_water) returning run_id into v_run;
  insert into public.workflow_remediation_cursors(run_id,high_water) values(v_run,p_high_water);
  return v_run;
end $$;

create or replace function public.hivemind_checkpoint_workflow_remediation(
 p_run_id bigint,p_expected_version integer,p_cursor bigint,p_high_water bigint,
 p_processed bigint,p_materialized bigint,p_skipped bigint,p_unavailable bigint,p_failed bigint,p_reason text,p_failed_resource_id bigint)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_version integer; v_status text;
begin
  if least(coalesce(p_processed,0),coalesce(p_materialized,0),coalesce(p_skipped,0),coalesce(p_unavailable,0),coalesce(p_failed,0)) < 0 then
    return jsonb_build_object('ok',false,'reason','negative_delta');
  end if;
  select version,status into v_version,v_status from public.workflow_remediation_runs where run_id=p_run_id for update;
  if not found then return jsonb_build_object('ok',false,'reason','missing_run'); end if;
  if v_status <> 'running' then return jsonb_build_object('ok',false,'reason','not_running','version',v_version); end if;
  if v_version is distinct from p_expected_version then return jsonb_build_object('ok',false,'reason','stale_version','version',v_version); end if;
  if p_reason is not null and p_reason not in ('corpus_path_unauthorized','conversion_error') then
    return jsonb_build_object('ok',false,'reason','bad_reason','version',v_version);
  end if;
  update public.workflow_remediation_cursors set cursor=coalesce(p_cursor,cursor),high_water=coalesce(p_high_water,high_water),last_reason=p_reason,updated_at=now() where run_id=p_run_id;
  update public.workflow_remediation_runs set version=version+1,high_water=coalesce(p_high_water,high_water),processed_count=processed_count+coalesce(p_processed,0),materialized_count=materialized_count+coalesce(p_materialized,0),skipped_count=skipped_count+coalesce(p_skipped,0),unavailable_count=unavailable_count+coalesce(p_unavailable,0),failed_count=failed_count+coalesce(p_failed,0),updated_at=now() where run_id=p_run_id returning version into v_version;
  if p_failed_resource_id is not null and p_reason is not null then
    insert into public.workflow_remediation_failures(run_id,resource_id,reason) values(p_run_id,p_failed_resource_id,p_reason)
    on conflict(run_id,resource_id) do update set attempts=public.workflow_remediation_failures.attempts+1,reason=excluded.reason,updated_at=now();
  end if;
  return jsonb_build_object('ok',true,'version',v_version,'status','running');
end $$;

create or replace function public.hivemind_complete_workflow_remediation(p_run_id bigint,p_expected_version integer)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_version integer; v_status text;
begin
 select version,status into v_version,v_status from public.workflow_remediation_runs where run_id=p_run_id for update;
 if not found then return jsonb_build_object('ok',false,'reason','missing_run'); end if;
 if v_status <> 'running' or v_version is distinct from p_expected_version then return jsonb_build_object('ok',false,'reason','stale_or_terminal','version',v_version,'status',v_status); end if;
 update public.workflow_remediation_runs set status='completed',version=version+1,completed_at=now(),updated_at=now() where run_id=p_run_id returning version,status into v_version,v_status;
 return jsonb_build_object('ok',true,'version',v_version,'status',v_status);
end $$;

revoke all on public.workflow_remediation_runs, public.workflow_remediation_cursors, public.workflow_remediation_failures from public;
revoke execute on function public.hivemind_create_workflow_remediation_run(bigint), public.hivemind_checkpoint_workflow_remediation(bigint,integer,bigint,bigint,bigint,bigint,bigint,bigint,bigint,text,bigint), public.hivemind_complete_workflow_remediation(bigint,integer) from public;
do $$ begin
 if exists(select 1 from pg_roles where rolname='anon') then execute 'revoke all on public.workflow_remediation_runs, public.workflow_remediation_cursors, public.workflow_remediation_failures from anon'; end if;
 if exists(select 1 from pg_roles where rolname='authenticated') then execute 'revoke all on public.workflow_remediation_runs, public.workflow_remediation_cursors, public.workflow_remediation_failures from authenticated'; end if;
 if exists(select 1 from pg_roles where rolname='service_role') then
   execute 'grant select,insert,update,delete on public.workflow_remediation_runs, public.workflow_remediation_cursors, public.workflow_remediation_failures to service_role';
   execute 'grant usage,select on sequence public.workflow_remediation_runs_run_id_seq to service_role';
   execute 'grant execute on function public.hivemind_create_workflow_remediation_run(bigint), public.hivemind_checkpoint_workflow_remediation(bigint,integer,bigint,bigint,bigint,bigint,bigint,bigint,bigint,text,bigint), public.hivemind_complete_workflow_remediation(bigint,integer) to service_role';
 end if;
end $$;
